services:

  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - suppliers-volume:/var/lib/postgres

    networks:
      - suppliers-network

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: dev1234

networks:
  suppliers-network:
    driver: bridge

volumes:
  suppliers-volume:
    driver: local